# Generated by Django 4.2.3 on 2023-09-02 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('duracion', models.IntegerField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer_url', models.URLField(default='')),
                ('fecha_estreno', models.DateField()),
                ('tipo', models.CharField(choices=[('Pelicula', 'Película'), ('Serie', 'Serie')], max_length=10)),
            ],
            options={
                'ordering': ['fecha_estreno'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('distribuidora', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('actores', models.TextField()),
                ('duracion', models.IntegerField()),
                ('anio_estreno', models.IntegerField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer_url', models.URLField(default='')),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')])),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PeliculasTaquilleras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('puesto', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('director', models.CharField(max_length=100)),
                ('distribuidora', models.CharField(max_length=100)),
                ('recaudacion_mundial', models.IntegerField()),
                ('presupuesto', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('anio_estreno', models.IntegerField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer_url', models.URLField(default='')),
            ],
            options={
                'ordering': ['puesto'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('temporadas', models.IntegerField()),
                ('capitulos', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('distribuidora', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('actores', models.TextField()),
                ('duracion', models.IntegerField()),
                ('anio_estreno', models.IntegerField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer_url', models.URLField(default='')),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')])),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Top10Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('puesto', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('genero', models.CharField(max_length=100)),
                ('temporadas', models.IntegerField()),
                ('capitulos', models.IntegerField()),
                ('presupuesto', models.IntegerField()),
                ('anio_estreno', models.IntegerField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer_url', models.URLField(default='')),
            ],
            options={
                'ordering': ['puesto'],
            },
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Pelicula', 'Película'), ('Serie', 'Serie')], max_length=10)),
                ('titulo_tipo', models.CharField(max_length=50)),
                ('contenido', models.CharField(max_length=500)),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')])),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
